//
//  AntiScambot_Response.swift
//  AntiScamChatbotApp
//
//

import Foundation


func getAntiScambotResponse(message: String) -> String {
    let tempMessage = message.lowercased()
    
    if tempMessage.contains("hello") {
        return "Hello, My name is AntiScambot,I am a chatbot that will \ngive users some preventive advice on Deception."
    } else if tempMessage.contains("give me advice") {
        return "Deception can take many forms, such as fraud, scams, and identity theft, and it can have serious consequences for individuals and businesses alike. Here are some general tips to help protect yourself from deception in Hong Kong: \n\n1. Be wary of unsolicited phone calls, emails, or text messages. Scammers often use these methods to try to trick people into giving them personal information or money. \n\n2. Keep your personal information private. Don't give out your personal details, such as your ID card number or bank account information, unless you are sure it is necessary and trustworthy. \n\n3. Use strong passwords and keep them secure. Avoid using the same password for multiple accounts and never share your passwords with anyone. \n\n4. Stay informed about the latest scams and frauds. Keep an eye on news and social media for any reports of new scams or frauds, and be cautious if you receive any suspicious messages or calls. \n\n5. Verify the identity of anyone who asks for your personal information or money. If someone claims to be from a company or organization, ask for their name, title, and contact information and verify their identity before providing any information or money.Remember, if something seems too good to be true or too suspicious, it probably is. \n\nAlways be cautious and take steps to protect yourself from deception.You can input [give me more advice] to ask more."
    } else if tempMessage.contains("give me more advice") {
        return "Certainly, I can provide more general advice on how to deal with deception if you believe you have already been deceived in Hong Kong: \n\n1. Contact the relevant authorities:\n If you believe you have been a victim of deception, you should contact the Hong Kong Police Force as soon as possible. They have a dedicated team to investigate such crimes, and they can help you with the necessary steps to report the incident.\n\n2 .Gather evidence:\n Try to gather as much evidence as possible, such as emails, messages, or any other communication that you had with the person or organization that deceived you. This evidence can be useful in the investigation and can help you prove your case.\n\n3. Notify your bank or credit card company:\n If you have provided any financial information to the person or organization that deceived you, you should notify your bank or credit card company immediately. They can help you take the necessary steps to protect your finances and prevent any further unauthorized transactions.\n\n4. Seek legal advice:\n If you have suffered any financial losses or damages as a result of the deception, you may want to seek legal advice. A lawyer can help you understand your legal rights and options for seeking compensation.\n\n5. Educate yourself:\n Finally, it is essential to educate yourself about the different types of deception and how to avoid them in the future.\n\nThis can help you protect yourself from similar incidents and prevent others from falling victim to deception as well."
    }else if tempMessage.contains("what can you do") {
            return "I can provide you with general information and advice on how to avoid or deal with deception in Hong Kong. However, please note that I am not a substitute for professional legal or financial advice.\n\nIf you have specific questions or concerns related to your situation, it is always best to consult with a qualified professional who can provide you with personalized advice and guidance.\n\nPlease let me know if you have any further questions or how else I can assist you.\n\nYou can input[phone call], [email], [online friend], [donate], [get message] to get advice to these targeted deception."
    }else if tempMessage.contains("talk about deception") {
            return "Sure, I can provide some information on deception.\n\nDeception is a term used to describe the act of intentionally misleading or tricking someone for personal gain. It can take many different forms, such as fraud, scams, or identity theft, and can have serious consequences for the victim, including financial losses, damage to reputation, and emotional distress.\n\nIn recent years, deception has become an increasingly common problem in Hong Kong, with scammers using a variety of tactics to deceive people, such as phone scams, phishing emails, and online scams. These scams often involve impersonating a reputable organization or government agency, and they can be very convincing.\n\nTo avoid falling victim to deception, it is essential to be aware of the different types of scams and tactics used by scammers. You should also be cautious when providing personal or financial information, especially if you are contacted by someone you do not know or if the request seems suspicious.\n\nIf you believe you have been deceived, it is important to take immediate action by contacting the relevant authorities and gathering evidence. You should also take steps to protect your financial accounts and seek legal advice if necessary.\n\nOverall, staying informed and vigilant is key to protecting yourself from deception in Hong Kong."
    }else if tempMessage.contains("phone call") {
            return "This could be a phone deception. The Hong Kong government would not ask for your personal information over the phone. Do not provide any personal information and hang up the phone. You can report the incident to the Hong Kong Police Force immediately."
    }else if tempMessage.contains("email") {
            return "This could be a phishing email, which is a common tactic used by scammers to obtain personal information. Do not click on any link or provide any personal information. Instead, contact your bank directly to confirm if the email is legitimate."
    }else if tempMessage.contains("online friend") {
            return "This could be a romance scam, which is a type of online scam that preys on people looking for love. Do not send any money or provide any personal information. Instead, report the incident to the Hong Kong Police Force and cut off all communication with the person."
    }else if tempMessage.contains("donate") {
            return "This could be a charity scam, which is a common tactic used by scammers to obtain money. Do not donate over the phone or provide any personal information. Instead, research the charity organization independently and donate directly through their official website or in person."
    }else if tempMessage.contains("get message") {
            return "This could be an impersonation scam, which is a type of online scam that preys on people's trust in their friends.\n\nDo not send any money or provide any personal information. Instead, contact your friend directly through another channel to confirm if the message is legitimate."
    }else if tempMessage.contains("bye") {
            return "You are welcome! I am honored to help you, I hope you can successfully avoid all deception! "
    }else if tempMessage.contains("what can i ask") {
            return "You may ask me:\n\n1. can you give me some advice\n\n2. what can you do\n\n3. can you talk about deception\n\n4. can you educate me about deception"
    }else if tempMessage.contains("other chatbot") {
            return "My role is to give users some preventive advice on deception. The role of Scammerbot is to imitate a scammer to talk with users.\nBut both of us aim to strengthen users' \ndefense against deception."
    }else if tempMessage.contains("can you educate") {
            return "Certainly, I can educate you with some information \nabout deception.\n\nDeception is the act of intentionally misleading or \ntricking someone for personal gain. It can take many \ndifferent forms, such as fraud, scams, or identity theft, and can have serious consequences for the victim, including financial losses, damage to reputation, and emotional distress.\n\nThere are many different types of deception, including:\n\n1. Phone scams: \nScammers may call victims and pretend to be from a reputable organization or government agency to obtain personal or financial information.\n\n2. Online scams: \nScammers may use email, social media, or other online platforms to trick victims into providing personal or financial information or to send money.\n\n3. Identity theft: \nScammers may steal someone's personal information, such as their name, address, or social security number, to open credit accounts or make fraudulent purchases.\n\n4. Investment scams: \nScammers may promise high returns on investment opportunities that are actually fraudulent.\n\n5. Romance scams: \nScammers may pose as potential romantic partners and ask for money or personal information from their victims.\n\nTo avoid falling victim to deception, it is important to be aware of the different types of scams and tactics used by scammers. You should also be cautious when providing personal or financial information, especially if you are contacted by someone you do not know or if the request seems suspicious.\n\nIf you believe you have been deceived, it is important to take immediate action by contacting the relevant authorities and gathering evidence. You should also take steps to protect your financial accounts and seek legal advice if necessary.\n\nOverall, staying informed and vigilant is key to protecting yourself from deception. I hope this information helps you understand more about deception. Let me know if you have any further questions or if there is anything else I can assist you with."
    } else {
        return "Sorry, I don't quite understand what you mean.\nYou may ask me:\n\n1. can you give me some advice\n\n2. what can you do\n\n3. can you talk about deception\n\n4. can you educate me about deception"
    }
}
